package presentation.ui

import androidx.compose.material3.adaptive.navigationsuite.ExperimentalMaterial3AdaptiveNavigationSuiteApi
import androidx.compose.material3.adaptive.navigationsuite.NavigationSuiteType
import androidx.compose.runtime.Composable

@OptIn(ExperimentalMaterial3AdaptiveNavigationSuiteApi::class)
@Composable
expect fun currentNavigationSuiteType(): NavigationSuiteType
