#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
LOCAL_PROPERTIES="${PROJECT_ROOT}/local.properties"
TARGET_FILE="${PROJECT_ROOT}/iosApp/Configuration/Config.private.xcconfig"

if [[ ! -f "${LOCAL_PROPERTIES}" ]]; then
  echo "Missing local.properties at ${LOCAL_PROPERTIES}" >&2
  exit 1
fi

get_prop() {
  local key="$1"
  local line
  line=$(grep -E "^${key}=" "${LOCAL_PROPERTIES}" | tail -n 1) || return 1
  echo "${line#*=}" | sed 's/\r$//'
}

write_assignment() {
  local xc_key="$1"
  local value="$2"

  printf "%s = %s\n" "${xc_key}" "${value}" >> "${TARGET_FILE}"
}

: > "${TARGET_FILE}"
{
  echo "// Generated by scripts/sync-ios-config.sh"
  echo "// Do not commit this file."
} >> "${TARGET_FILE}"

error_count=0

# Resolve required values
gid_client_id="$(get_prop "GOOGLE_IOS_CLIENT_ID")" || { echo "Missing 'GOOGLE_IOS_CLIENT_ID' in local.properties" >&2; ((error_count++)); }
gid_server_client_id="$(get_prop "GOOGLE_SERVER_CLIENT_ID")" || { echo "Missing 'GOOGLE_SERVER_CLIENT_ID' in local.properties" >&2; ((error_count++)); }
gid_url_scheme="$(get_prop "GOOGLE_IOS_URL_SCHEME")" || { echo "Missing 'GOOGLE_IOS_URL_SCHEME' in local.properties" >&2; ((error_count++)); }
revenue_cat_key="$(get_prop "REVENUECAT_IOS_KEY")" || { echo "Missing 'REVENUECAT_IOS_KEY' in local.properties" >&2; ((error_count++)); }

# Backend host with fallback from url
backend_host="$(get_prop "vokab.backend.host" 2>/dev/null || true)"
if [[ -z "${backend_host}" ]]; then
  backend_url="$(get_prop "vokab.backend.url" 2>/dev/null || true)"
  if [[ -n "${backend_url}" ]]; then
    backend_host="${backend_url#https://}"
    backend_host="${backend_host#http://}"
    backend_host="${backend_host%%/*}"
  fi
fi
if [[ -z "${backend_host}" ]]; then
  echo "Missing 'vokab.backend.host' or 'vokab.backend.url' in local.properties" >&2
  ((error_count++))
fi

# Write assignments
write_assignment "GID_CLIENT_ID" "${gid_client_id}" || ((error_count++))
write_assignment "GID_SERVER_CLIENT_ID" "${gid_server_client_id}" || ((error_count++))
write_assignment "GID_URL_SCHEME" "${gid_url_scheme}" || ((error_count++))
write_assignment "REVENUECAT_IOS_KEY" "${revenue_cat_key}" || ((error_count++))
write_assignment "REVENUECAT_ANDROID_KEY" "${revenue_cat_key}" || ((error_count++))
write_assignment "VOKAB_BACKEND_HOST" "${backend_host}" || ((error_count++))

if (( error_count > 0 )); then
  echo "Config generation failed. Populate the missing keys above." >&2
  rm -f "${TARGET_FILE}"
  exit 1
fi

echo "Generated ${TARGET_FILE}"

